### ISSUE TITLE
to_sigma.py of own .cosmo files generated by Gaussian09?

### ISSUE THREAD

**Issue by y-kusaka** [usnistgov/COSMOSAC#5]
I'm new to COSMO-SAC and COSMO-RS. It would be nice to have functionality for converting own .cosmo files other than DMol3 though this project seems dedicated to the UD and VT databases... [g09w_ref.cosmo.txt](https://github.com/usnistgov/COSMOSAC/files/5049868/g09w_ref.cosmo.txt) is a .cosmo file generated Gaussian09.

**Comment by ianhbell** [comment]
Good question, I had long intended to add support for cosmo files from other software tools - of course you should also be aware that the COSMO models tend to be parameterized according to a particular software tool's COSMO calculations, so it is not as simple as a drop-in with a .cosmo file from Gaussian09.  Can you please provide the units for all the quantities in the cosmo file?  There are many potential pitfalls with units these files, especially around charge and area.  Did you read our paper: https://pubs.acs.org/doi/pdf/10.1021/acs.jctc.9b01016 ?

________________________________

**Comment by y-kusaka** [comment]
Thank you for reply. I red the paper and understood the unit problem (angstroms and Bohr units). I need to look into .cosmo files of Gaussian09 to provide information since I'm not quite familiar with Gaussian and other formats for molecular structure descriptions.

**Comment by ianhbell** [comment]
Great, if you can figure out all the units, then I can write a parser to pull out the requisite bits and pieces.

**Comment by y-kusaka** [comment]
I just sent an e-mail directly to @ianhbell about the format.

**Comment by ianhbell** [comment]
Here is the relevant info we need about the variables and their units:

$cosmo_data
- "fepsi" = scaling factor for charges in conductor model. "fepsi=1" if XCosmo<0 (i.e. infinite dielectric limit), otherwise "fepsi=(EPS - 1) / (EPS + XCosmo)".
- "nps" = number of segments (number of discretization elements of the solute cavity surface)
- "area" = area of the solute cavity surface (in Bohr^2)
- "volume" = volume enclosed by the solute cavity surface (in Bohr^3)

$coord_rad
- X,Y,Z = atomic Cartesian coordinates in Bohr
- radius = atomic sphere radius in Angstrom
- area = area of atomic sphere exposed to solute-solvent interface in Angstrom^2
- COSMO charge = atomic COSMO charge in electron
- sigma = charge density (charge/area) in electron/Angstrom^2

$coord_car
- atomic Cartesian coordinates in Angstrom

$screening_charge
- charges are in electron

$cosmo_energy
- energies are in Hartree

$segment_information
- position (X,Y,Z) = Cartesian coordinates of each surface segment in Bohr
- charge = point charge mapped onto each surface segment in electron (corrected meaning that they are scaled by "fepsi")
- area = area of each surface segment in Angstrom^2
- charge/area = (sigma) charge density on each surface segment in electron/Angstrom^2
- potential =  potential on each surface segment in Hartree

**Comment by ianhbell** [comment]
Closed by #7
